# -*- coding: utf-8 -*-
"""first_python_program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104oDDPjCJjDSQxYQfV4czOvLByCxHfhS

**My first program**
"""

a = 12
b = 2

a

b

"""you can write something"""

print(a)

"""#**My first program in Python**"""

a = 3
b = 4
c = 'b'
d = 'hello'
f = 4.6
print("\n\nHello world !")

print(2+2)

print('"Francesco" is one the teachers of this academy\'s workshop')

print(a, b)

'''This 
is 
a comment
'''

# the is the sigle line code 
# ghhgh

number = input("Insert one number please: ")
number = int(number)

type(number)

name = input("Insert a name: ")

print(number)
print(name)